### ISSUE TITLE
stoi was not declared in this scope

### ISSUE THREAD

**Issue by tuanpham996** [nicexe/Computer-Security-Task-1#1]
when i run this program on DevC++, I got a issue: " [error] 'stoi' was not declared in this scope". Can you give me a solution! thanks

**Comment by nicexe** [comment]
Have a look here: [CMakeLists.txt #4](https://github.com/nicexe/Computer-Security-Task-1/blob/master/CMakeLists.txt#L4)

When I wrote this ~3 years ago I used the `c++11` version. I was under the impression that the code I wrote was fairly portable. Good thing my professor didn't deduct any points for this task.

You should probably use more modern standards and maybe do some checks in case something goes wrong.

**Comment by nicexe** [comment]
I just tried building this project and using it as well. It seems like its working without any problems.

![screen shot 2018-02-05 at 7 09 00 pm](https://user-images.githubusercontent.com/867535/35818210-195b7b78-0aa8-11e8-93c0-6970e62b87ee.png)
